### ISSUE TITLE
Attributes creation_date_start and creation_date_end not working

### ISSUE THREAD

**Issue by Schiocco** [lightninglabs/lightning-api-ng#12]
When calling /v1/payments via REST API the Attributes creation_date_start and creation_date_end are ignored and they are not working. It always returns all invoices.

**Comment by guggero** [comment]
Those fields were only added recently and aren't contained in a release yet. They will work with 0.16.0 which should be coming out very soon.

**Comment by Schiocco** [comment]
The fastest support ever. Great news!

**Comment by guggero** [comment]
With 0.16.0 being released, I'm closing this now.
