### ISSUE TITLE
Cron job to update API website does not appear to be running.

### ISSUE THREAD

**Issue by CRex15** [lightninglabs/lightning-api-ng#21]
The following API references are not building against the master branches according to README. They are all referencing commits that are were pushed ~1 month ago.

LND, Loop, Taproot Assets Protocol, Lightning Terminal (LiT)

**Comment by guggero** [comment]
Ah yes, something seems to be failing. Thanks for the report, I'll look into it.

**Comment by guggero** [comment]
Kicked the cron job again, there seems to be a second issue, being addressed here: https://github.com/lightninglabs/taproot-assets/pull/413

**Comment by guggero** [comment]
This is now actually fixed (https://github.com/lightninglabs/taproot-assets/pull/413), cron job is active again.
