### ISSUE TITLE
Api Website does not resolve special characters like \' correctly

### ISSUE THREAD

**Issue by ziggie1984** [lightninglabs/lightning-api-ng#24]
While reviewing https://github.com/lightningnetwork/lnd/pull/8181 I realized that we have several cases where the characters are not resolved right, one example:

<img width="848" alt="Screenshot 2023-11-17 at 11 26 24" src="https://github.com/lightninglabs/lightning-api-ng/assets/90319354/834f3349-1d69-430a-a851-4286a4fe001c">

**Comment by jamaljsr** [comment]
Thanks for the heads up. I'll look into this soon.
