### ISSUE TITLE
Can't select REST, shell, or python code sample tabs OR field accordions in chromium based browsers

### ISSUE THREAD

**Issue by huumn** [lightninglabs/lightning-api-ng#29]
<img width="276" alt="Screenshot 2024-08-01 at 11 56 34 AM" src="https://github.com/user-attachments/assets/e69f016f-34f7-4588-ac88-3f0ed0b083a4">

It works fine in Safari, but not Brave or Chrome.

**Comment by jamaljsr** [comment]
I just tested in Chrome, Brave, Safari, Edge and Firefox on my ARM Mac and didn't have any issues switching tabs.

Are you using any browser plugins that may be conflicting with the JS on the page? Can you check the browser DevTools Console to see if there are any errors logged?

**Comment by huumn** [comment]
It's working fine for me now. If you all didn't change anything, it must've been something weird on my end.

I'll close. Sorry if this was a false alarm.
