### ISSUE TITLE
How can I get macaroon_root_key?

### ISSUE THREAD

**Issue by progressorTCH** [lightninglabs/lightning-api-ng#4]
I want backup channel and restore channel. But I found that the recovery failed, so I guessed that it was because of different macaroons, so I found that macaroon_root_key can be set in the initwallet method. Then, I searched all the methods in the api, but I didn't find a way to get macaroon_root_key, so I want to know how to get macaroon_root_key.

**Comment by jamaljsr** [comment]
Hey @progressorTCH this repo is for the API docs websites. For help with using LNC, you should open an issue in the [lightningnetwork/lnd](https://github.com/lightningnetwork/lnd) repo instead. Going to close this one out.

**Comment by progressorTCH** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
